version: 2
jobs:
  math-test:
    docker:
      - image: circleci/python:3.5.2
    steps:
      - checkout
      - run:
        name: Thisisatest 
        command: |
          pip install -r requirements.txt 
          nosetests tests/math-test.py
workflows:
  version: 2
  build-tests:
    jobs:
      - math-test
