version: 2
jobs:
  math-test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables // its your workflow step"
          command: |
          pip install -r requirements.txt
        
workflows:
  version: 2
  build-tests:
    jobs:
      - math-test
