version: 2
jobs:
  math-test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: pip install --user -r requirements.txt 
        command: nosetests tests/math-test.py 
        
workflows:
  version: 2
  build-tests:
    jobs:
      - math-test
