version: 2
jobs:
  math-test:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables // its your workflow step"
          command: pip install --user -r requirements.txt
      - run: 
          name: "doing the test"
          command: nosetests test/math-test.py
      - run: 
          name: "Generate report"
          command: coverage run src/*.py && coverage report
                
workflows:
  version: 2
  build-tests:
    jobs:
      - math-test
