version: 2
jobs:
  math-test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: # base image is python, so we run `nosetests`, an extension of `unittest`
          command: nosetests tests/math-test.py 
        
workflows:
  version: 2
  build-tests:
    jobs:
      - math-test
