version: 2
jobs:
  math-test:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run: 
        command: nosetests tests/math-test.py 
        
workflows:
  version: 2
  build-tests:
    jobs:
      - math-test
